### ISSUE TITLE
SynthInstrument::removeEvent should remove event from audioEvents (and liveAudioEvents?) isnt't it?

### ISSUE THREAD

**Issue by hypeastrum** [igorski/MWEngine#10]
Now it's delete event (if not jni mode) but not removes it from vectors.

**Comment by igorski** [comment]
@hypeastrum I had to overthink this for a while. I can understand the confusion as the interface is currently silly, and probably because of the naming convention!

Instead of calling removeEvent() directly on an AudioEvent, you must invoke setDeletable( true ); this will ensure that the event is not deleted while it is playing back causing a violent crash (which is likely when the buffer size is low).

When an event is marked as deletable, the Sequencer will pick this up and remove the events from the audioEvents / liveEvents vector (see _if removes.size() > 0_) in both _collectSequencedEvents_ and _collectLiveEvents_ inside sequencer.cpp. After which the SynthInstrument removeEvent will delete it (when not using JNI). I will move the splicing from the events array logic into the instrument, as it belongs there, this will however not change the "deletion interface" from an AudioEvent perspective.

The reason btw. that an event is not deleted when using JNI, is that if you break the reference to the event in Java, it will be garbage collected and JNI will automatically call the destructor freeing the memory in the native layer.

I hope this solves any questions you had (basically use _setDeletable( true )_ instead of _removeEvent()_) and I will think how to clean this up to make more sense and avoid confusion (more likely an update in the Wiki is necessary).

**Comment by hypeastrum** [comment]
Hm. Thanks for information! I think, you prevented several possible bugs…

**Comment by igorski** [comment]
BaseInstruments can now remove the event from the event vectors (previously the Sequencer did this, which was silly). Updated the Wiki pages and unit tests accordingly.
