### ISSUE TITLE
import issues

### ISSUE THREAD

**Issue by scar20** [igorski/MWEngine#131]
Once in a while, it happen that the import statement get screwed up.
 I have:
import nl.igorski.mwengine.MWEngine;
import nl.igorski.mwengine.core.BaseAudioEvent;
etc...
first statement appear OK
but for all the rest, they appear greyed out with "core" in red.
So then all the rest of the file is full of red.
But it compile and run & install..... wtf
What can cause this very annoying thing to happen? Any ideas?

**Comment by igorski** [comment]
It is expected that upon opening the project for the first time any imports from the _nl.igorski.mwengine.core.*_ namespace can't be resolved as the contents of this namespace are [generated by the build](https://github.com/igorski/MWEngine/wiki/Troubleshooting-MWEngine#cannot-find-java-classes-in-nligorskimwenginecore).

When running the Gradle target _:mwengine:assemble_ the files should be generated as evident by your successful run and install.

If you are using Android Studio as your IDE, it is sometimes necessary to close / reopen the project in order to see the files present. This depends a little on the cached contents of your project folder.

**Comment by scar20** [comment]
Ok, I could not do as the troubleshoot suggest "Unmark this directory as sources root" so after trying many thing like "Invalidate caches/Restart" I was about to downgrade to AndroidStudio 4.1xx (since this one was working fine) then I tryed "Refresh Linked C++ Project" in the Build menu. Ahhhh that worked!

**Comment by igorski** [comment]
Hm, the cache refresh should usually do it. It's a "feature" of the Jetbrains IDE's that sometimes occurs regardless of project type. It should be fine once the files have been "seen" on the filesystem and are in the project cache.

If you don't mind, I'll close the issue as the origin of the problem lies outside of the scope of MWEngine.
