### ISSUE TITLE
Error with processors 

### ISSUE THREAD

**Issue by YogarajRamesh** [igorski/MWEngine#159]
Hi @igorski 
   1.   I am try to add processor to getInputChannel() but i got error  
  **error: cannot find symbol
         dcfilter = new DCOffsetFilter(1); 
         ^    symbol:   variable dcfilter**
   Code snippet
       private DCOffsetFilter dcfilter;
      dcfilter = new DCOffsetFilter(1); 
     _engine.getInputChannel().getProcessingChain().addProcessor(dcfilter );

  

    2. I am trying to add “reverb” to getInputChannel() while using OUTPUT_CHANNELS = 2 is working fine but while using OUTPUT_CHANNELS = 2  i got error  
       Terminating with uncaught exception of type std::out_of_range: vector

Thanks in advance

**Comment by igorski** [comment]
Hi @YogarajRamesh 

For #1, turns out the DC offset filter was not exposed to the Java API. This has been addressed in fec41190772f5b42761834ad05017114c80c96e5

For #2, the legacy reverb effect wasn't mono compatible, which all processors in MWEngine actually should be. This has been addressed in d539a6f6d9fce3e8fa40d08b8227cfe10b06ffa3
