### ISSUE TITLE
Position notification improvements

### ISSUE THREAD

**Issue by hypeastrum** [igorski/MWEngine#17]
1) When sequencer started, first notification will be about position 1. So, in demo app position changed from 1 to 15, and then from 0 to 15. If I need some events to sync with audio, notifications about 0 position at start simplifies client code. 

2) If I need to sync with audio with best precision, I need also position start offset in buffer. I've implemented this feature in my fork (https://github.com/songsterr/MWEngine/commit/86ad204c5d54707eaa04a05e4cb5c3ffa7b06b2d). We can talk about it. Now API is not so good, but can be improved in java part of lib.

**Comment by igorski** [comment]
Ah, well spotted! Hadn't seen that! I'm currently on holiday without a computer until Dec 8th, but we can discuss in the meantime. Can you explain the use case of point #2 as I'm confused about that one.

**Comment by hypeastrum** [comment]
About 2):
I need to sync music beats with UI events (animation) and user feedback (touches). 
I've no problem on devices with low latency. 
But on my Xperia S latency is too high, about 250ms. 
I've divided bar with 48 subdivisions to put 16th and triplets.
WIth 4/4 and tempo 90bpm time gap between subdivisions is 60*1000/90*4/48 = 55ms. It less than latency and less than buffer size. So position updates happens more than one time for buffer write, with no delay.
I need information about sample count before position update to sync my app with music perfectly. I can add calculated delays for my events, if I need to sync it perfectly.

**Comment by igorski** [comment]
Makes a lot of sense! So in your proposed fix in your fork you'll take care of the actual calculation in Java? Works for me, as the very purpose of this update is to sync UI. I'll be sure to take the changes from your fork, update the Wiki and example accordingly and givr you credit for your contributions when I get back. :)

**Comment by hypeastrum** [comment]
> So in your proposed fix in your fork you'll take care of the actual calculation in Java?
Yes, API just provides information. 

Calling observer at exact time would be much better, but seems to be much harder task.

**Comment by igorski** [comment]
@hypeastrum all back and ready to get to work :)

I've been looking at your fork and like a lot of your improvements! (the conditionals on the recording buffers in particular!)

I have a question regarding your changes to the _handleSequencerPositionUpdate()_ method. Instead of passing the timestamp (which was indeed unused), you now pass to the sample position within a range of 0 - BUFFER_SIZE of the engine. My question is what is the result of the:

    ( stepPosition << 16 ) | pendingSamplingCount )

...bitwise calculation, wouldn't the value of _bufferPosition_ be enough to pass via JNI ? You could then determine the current step position using _Math.floor( bufferPosition / MWEngine.BYTES_PER_TICK )_ and the "progress" into the next step by calculating the amount of samples that are pending, e.g. : _( nextBufferPosition * MWEngine.BYTES_PER_TICK ) - bufferPosition_

perhaps I'm not sure how you're treating the value in your application in Java :)

**Comment by hypeastrum** [comment]
Hi! I've spend nice holidays too =) and ready to work again

The way you suggested should work too. API will be more accurate. 
What about making some low level engine params  (incl. bufferPosition) accessible through special java class?

**Comment by igorski** [comment]
@hypeastrum : I finally got around to make the changes. I have taken some of your optimizations of the engine, as well as worked on your request regarding the position notifications.

Could you review the branch "position-notification" (see pull request https://github.com/igorski/MWEngine/pull/18 for details), basically the notification now broadcasts the current buffer position to Java, and you can use new getters inside SequencerController to retrieve the buffer position, samples per bar/beat, etc. type values. Are these sufficient or would you need more engine properties exposed to Java ?

**Comment by igorski** [comment]
Changes merged to master.
