### ISSUE TITLE
Unit Tests - Running / Develop

### ISSUE THREAD

**Issue by teotigraphix** [igorski/MWEngine#73]
Hey,

I use Windows for dev, is there any advice you can give for a setup? I am trying to figure out how to use Android Studio as the IDE with code completion/error checking and run a single test or the whole suite.

* Do you just use a text editor and "run" in place?
* How do you run 1 test at a time when you are doing TDD (mind you I do this but not as religion)?
* I have tried to understand how AS works with NDK testing but it doesn't seem to jive with what you have going.

**Comment by igorski** [comment]
Currently running the suite is done by manually invoking the _test.sh_ shell script. Haven't invested any time in how this can be done directly from Android Studio as it should be possible (assumption) to run on a per-file basis, rather than the whole suite at once. For intermediate single tests, I only include the test I'm working on in _main.cpp_.

This can be improved once https://github.com/igorski/MWEngine/issues/93 completes.

**Comment by igorski** [comment]
This will be tackled as part of #106, together with #93 this ensures that unit tests can be written and executed side-by-side during development without requiring custom scripts or configuration changes.
