### ISSUE TITLE
C++ Convention - 0 used as null pointer

### ISSUE THREAD

**Issue by teotigraphix** [igorski/MWEngine#74]
Is this legacy in the code that you use `0` as `nullptr`?

I am coding convention OCD sometimes and I have read not using `nullptr` is bad form.

Here again, I am just getting into the deeper nuances of C++ now and I want to do things correct.

**Comment by igorski** [comment]
That's an interesting observation, in previous NDK versions _nullptr_ wasn't part of the STL of choice (which is hardly an excuse as it was _#define_ away). It is indeed confusing that numerical 0 is used instead of _nullptr_ (even though they imply the same on a technical level, it is confusing if anything to read).

**Comment by teotigraphix** [comment]
Yes, it was due to the fact your code reads so well and the 0 for nullptr was like not having a period or comma. 

Nothing earth shattering but, you know. :)
