### ISSUE TITLE
Low volume for events added to sequencer 

### ISSUE THREAD

**Issue by robtize** [igorski/MWEngine#79]
Seems like the volume for events added to the sequencer are a lot lower than live events

**Comment by igorski** [comment]
There is bit in the audio engine where summing live events multiplies their volume. Not entirely sure what the rationale here was, I think it is lingering code from before the volume summing was refactored. There is no reason this should behave differently between live and synthesized events, as they belong to the same instrument.

**Comment by igorski** [comment]
Just to be clear: the sequenced events weren't "low in volume", the live ones were super loud (due to a scaling bug, instead of decreasing volume when lowering a live events volume, it would actually increase!) Keep this in mind if you're disappointed with the sudden decrease in violent impact :)

Give this feature branch a spin: https://github.com/igorski/MWEngine/pull/85

**Comment by robtize** [comment]
Thanks once again Igor! Will try this out tonight when I get home and give
an update!

**Comment by teotigraphix** [comment]
Ha, I was using live events with sequenced events yesterday and noticed this, now it makes sense what was happening.
