### ISSUE TITLE
Stress Testing DSP

### ISSUE THREAD

**Issue by teotigraphix** [igorski/MWEngine#82]
Hi,

I was curious if you have tried to break this on devices to see how many oscillators etc. you can have going.

This is more just an informative question.

If you haven't I guess I will, I have a Pixel and Samsung tablet that I will test on (and my other beta testers).

**Comment by igorski** [comment]
That's quite a while ago on far less powerful devices than the average consumer currently has. No more interesting rather than profiling the CPU usage for MikroWave (which on a dual core Galaxy wouldn't break a sweat when all possible processors in the chain were activated). Though the pitchshifter processor is quite heavy, mind you!

There are no individual benchmarks for the processors available, also keep in mind that different CPU architectures might perform differently.

Good practice would always be to test within the context of your application, as other factors outside of the engine will also come into play (your graphics rendering or background processes for instance).

**Comment by teotigraphix** [comment]
Interesting Table for device performance of pro audio.

https://juce.com/discover/stories/Mobile%20performance%20index%20
