### ISSUE TITLE
sizeof(long) equal 8

### ISSUE THREAD

**Issue by stylixpro** [igorski/MWEngine#97]
fileSize in wav_header is long type.
In my phone(Xiaomi Mi A2 Lite), sizeof(long) returns 8.
So, it cannot read wav file properly.
There are a lot of long type variables in source code.
How can I fix it?

**Comment by igorski** [comment]
Hi there.

It is correct that the long data type corresponds to being 8 bytes (64 bits) in size. As such, the Xiaomi should present no problem.

What is the exact issue you are experiencing ? Is there a WAV file that fails to load correctly ? Could you give some steps to reproduce the issue and what your expectation is ?

**Comment by stylixpro** [comment]
Line 93 in wavereader.cpp, 
header.fileType is RIFF but header.format, header.formatName are garbage values.

filzeSize of wav_header is 8 bytes. so
fread( &header, sizeof( header ), 1, fp );
cannot read header properly.

In my other phone (Galaxy S4) it works good.

**Comment by igorski** [comment]
Ah the mention of the S4 and it working there helps. The S4 uses ARMv7 as the architecture and the Xiaomi ARMv8-A. If in _Application.mk_ the APP_ABI _arm64-v8a_ is enabled (it is by default) and the build instructions are used as described in the README file, the engine should build for that ARMv8-A processor, meaning that it will run an actual 64-bit version of the library instead of running in compatibility mode (where a long for 32-bit architecture is actually 4 bytes!).

I have to think about creating a compiler preprocessor for this use case. Can you verify whether loading the WAV works on both devices if you replace all declarations of _unsigned long_ (in _struct wav_header_ in _wavereader.cpp_) with _unsigned int_ ?

**Comment by igorski** [comment]
Ingore my last message. Can you pull the latest master branch ? In [the latest commit](https://github.com/igorski/MWEngine/commit/43afe5ed50a24e53ebac907332b183c62c05255f) I have added a fix where integer data types are used explicitly with their expected data size where applicable (e.g. wave reading).

**Comment by igorski** [comment]
Closing as this has been verified by others to address the issue described here.
